### ISSUE TITLE
NotAnAttrsClassOrDataclass: <class 'list'> 

### ISSUE THREAD

**Issue by cvlvxi** [python-desert/desert#7]
I'm getting the following error when I try to create a schema from the following:

```

from dataclasses import dataclass, field
from typing import *
import desert


@dataclass
class Reference:
    reference: str = ""

@dataclass
class Code:
    code: str = ""
    system: str = ""
    display: str = ""

@dataclass
class Coding:
    coding: List[Code]


@dataclass
class Type:
    coding: Coding


@dataclass
class Input:
    type: Type
    valueString: str

@dataclass
class ExecutionPeriod:
    start: str

@dataclass
class BusinessStatus:
    coding: List[Coding]

@dataclass
class TaskResponse:
    basedOn: List[Reference]
    businessStatus: BusinessStatus
    code: Coding
    description: str
    executionPeriod: ExecutionPeriod
    id: str
    input: List[Input]
    intent: str
    output: list
    requester: dict
    resourceType: str
    status: str

 schema = desert.schema(TaskResponse)
```

```
Traceback (most recent call last):
  File "tests/xxx/test.py", line 50, in test_task_response
    schema = desert.schema(TaskResponse)
  File "/xxx/python_env/py3/py3env/lib/python3.7/site-packages/desert/__init__.py", line 24, in schema
    return desert._make.class_schema(cls, meta=meta)(many=many)
  File "/xxx/python_env/py3/py3env/lib/python3.7/site-packages/desert/_make.py", line 122, in class_schema
    field.metadata,
  File "/xxx/python_env/py3/py3env/lib/python3.7/site-packages/desert/_make.py", line 260, in field_for_schema
    nested = forward_reference or class_schema(typ)
  File "/xxx/python_env/py3/py3env/lib/python3.7/site-packages/desert/_make.py", line 110, in class_schema
    raise desert.exceptions.NotAnAttrsClassOrDataclass(clazz)
desert.exceptions.NotAnAttrsClassOrDataclass: <class 'list'>
```

Not sure why it's saying class: 'list' when it's defined as a dataclass as you can see above?

**Comment by python-desert** [comment]
`list` is intended to be typed as a generic, such as `List[int]`. The latest version, `2019.12.10` gives a better error message. Fyi https://pypi.org/project/marshmallow-dataclass/ is the project this one was originally based on.
